package types

// LogType represents command logging types.

const (
	LOG_NORMAL = iota
	LOG_ALWAYS
	LOG_NEVER
	LOG_BUILD
	LOG_HIGH
	LOG_COMM
	LOG_WARN
	LOG_BUG
	LOG_ALL
)

// StanceType represents stance types.

const (
	STANCE_NONE = iota
	STANCE_NORMAL
	STANCE_VIPER
	STANCE_CRANE
	STANCE_CRAB
	STANCE_MONGOOSE
	STANCE_BULL
	STANCE_MANTIS
	STANCE_DRAGON
	STANCE_TIGER
	STANCE_MONKEY
	STANCE_SWALLOW
	MAX_STANCE
)

// BASIC_STANCE is one more than the last basic stance.
const BASIC_STANCE = STANCE_MANTIS

// int represents return types for move_char, damage, etc.

const (
	rNONE = iota
	rCHAR_DIED
	rVICT_DIED
	rBOTH_DIED
	rCHAR_QUIT
	rVICT_QUIT
	rBOTH_QUIT
	rSPELL_FAILED
	rOBJ_SCRAPPED
	rOBJ_EATEN
	rOBJ_EXPIRED
	rOBJ_TIMER
	rOBJ_SACCED
	rOBJ_QUAFFED
	rOBJ_USED
	rOBJ_EXTRACTED
	rOBJ_DRUNK
	rCHAR_IMMUNE
	rVICT_IMMUNE

	rCHAR_AND_OBJ_EXTRACTED int = 128
	rERROR                  int = 255
)

// int represents connected state for a channel.

const (
	CON_PLAYING = iota
	CON_GET_NAME
	CON_GET_OLD_PASSWORD
	CON_CONFIRM_NEW_NAME
	CON_GET_NEW_PASSWORD
	CON_CONFIRM_NEW_PASSWORD
	CON_GET_NEW_SEX
	CON_GET_NEW_CLASS
	CON_READ_MOTD
	CON_GET_NEW_RACE
	CON_GET_EMULATION
	CON_EDITING
	CON_GET_WANT_RIPANSI
	CON_TITLE
	CON_PRESS_ENTER
	CON_WAIT_1
	CON_WAIT_2
	CON_WAIT_3
	CON_ACCEPTED
	CON_GET_PKILL
	CON_READ_IMOTD
	CON_REDIT
	CON_OEDIT
	CON_MEDIT
	CON_COPYOVER_RECOVER
)

// int represents character substates.

const (
	SUB_NONE = iota
	SUB_PAUSE
	SUB_PERSONAL_DESC
	SUB_BAN_DESC
	SUB_OBJ_SHORT
	SUB_OBJ_LONG
	SUB_OBJ_EXTRA
	SUB_MOB_LONG
	SUB_MOB_DESC
	SUB_ROOM_DESC
	SUB_ROOM_EXTRA
	SUB_ROOM_EXIT_DESC
	SUB_WRITING_NOTE
	SUB_MPROG_EDIT
	SUB_HELP_EDIT
	SUB_WRITING_MAP
	SUB_PERSONAL_BIO
	SUB_REPEATCMD
	SUB_RESTRICTED
	SUB_DEITYDESC
	SUB_MORPH_DESC
	SUB_MORPH_HELP
	SUB_PROJ_DESC
	SUB_JOURNAL_WRITE
	SUB_NEWS_POST
	SUB_NEWS_EDIT

	SUB_TIMER_DO_ABORT   int = 128
	SUB_TIMER_CANT_ABORT int = 129
)

// Sunint represents time-of-day sun positions.

const (
	SUN_DARK = iota
	SUN_RISE
	SUN_LIGHT
	SUN_SET
)

// SkyCondition represents weather sky conditions.

const (
	SKY_CLOUDLESS = iota
	SKY_CLOUDY
	SKY_RAINING
	SKY_LIGHTNING
)

// ToType represents target types for act().

const (
	TO_ROOM = iota
	TO_NOTVICT
	TO_VICT
	TO_CHAR
	TO_CANSEE
)

// int represents color action types (starting at 1024).

const (
	AT_COLORBASE int = 1024
	AT_PLAIN     int = AT_COLORBASE
	AT_ACTION    int = AT_COLORBASE + 1
	AT_SAY       int = AT_COLORBASE + 2
	AT_GOSSIP    int = AT_COLORBASE + 3
	AT_YELL      int = AT_COLORBASE + 4
	AT_TELL      int = AT_COLORBASE + 5
	AT_WHISPER   int = AT_COLORBASE + 6
	AT_HIT       int = AT_COLORBASE + 7
	AT_HITME     int = AT_COLORBASE + 8
	AT_IMMORT    int = AT_COLORBASE + 9
	AT_HURT      int = AT_COLORBASE + 10
	AT_FALLING   int = AT_COLORBASE + 11
	AT_DANGER    int = AT_COLORBASE + 12
	AT_MAGIC     int = AT_COLORBASE + 13
	AT_CONSIDER  int = AT_COLORBASE + 14
	AT_REPORT    int = AT_COLORBASE + 15
	AT_POISON    int = AT_COLORBASE + 16
	AT_SOCIAL    int = AT_COLORBASE + 17
	AT_DYING     int = AT_COLORBASE + 18
	AT_DEAD      int = AT_COLORBASE + 19
	AT_SKILL     int = AT_COLORBASE + 20
	AT_CARNAGE   int = AT_COLORBASE + 21
	AT_DAMAGE    int = AT_COLORBASE + 22
	AT_FLEE      int = AT_COLORBASE + 23
	AT_RMNAME    int = AT_COLORBASE + 24
	AT_RMDESC    int = AT_COLORBASE + 25
	AT_OBJECT    int = AT_COLORBASE + 26
	AT_PERSON    int = AT_COLORBASE + 27
	AT_LIST      int = AT_COLORBASE + 28
	AT_BYE       int = AT_COLORBASE + 29
	AT_GOLD      int = AT_COLORBASE + 30
	AT_GTELL     int = AT_COLORBASE + 31
	AT_NOTE      int = AT_COLORBASE + 32
	AT_HUNGRY    int = AT_COLORBASE + 33
	AT_THIRSTY   int = AT_COLORBASE + 34
	AT_FIRE      int = AT_COLORBASE + 35
	AT_SOBER     int = AT_COLORBASE + 36
	AT_WEAROFF   int = AT_COLORBASE + 37
	AT_EXITS     int = AT_COLORBASE + 38
	AT_SCORE     int = AT_COLORBASE + 39
	AT_RESET     int = AT_COLORBASE + 40
	AT_LOG       int = AT_COLORBASE + 41
	AT_DIEMSG    int = AT_COLORBASE + 42
	AT_WARTALK   int = AT_COLORBASE + 43
	AT_RACETALK  int = AT_COLORBASE + 44
	AT_IGNORE    int = AT_COLORBASE + 45
	AT_DIVIDER   int = AT_COLORBASE + 46
	AT_MORPH     int = AT_COLORBASE + 47
	AT_SHOUT     int = AT_COLORBASE + 48
	AT_MUSE      int = AT_COLORBASE + 49
	AT_QUEST     int = AT_COLORBASE + 50
	AT_ASK       int = AT_COLORBASE + 51
	AT_THINK     int = AT_COLORBASE + 52
	AT_STANCE    int = AT_COLORBASE + 53
	AT_AVATAR    int = AT_COLORBASE + 54
	AT_MUSIC     int = AT_COLORBASE + 55
	AT_TOPCOLOR  int = AT_COLORBASE + 56
)

// AT_MAXCOLOR is the number of color types.
const AT_MAXCOLOR = AT_TOPCOLOR - AT_COLORBASE

// int represents player races.

const (
	RACE_HUMAN int = iota
	RACE_ELF
	RACE_DWARF
	RACE_HALFLING
	RACE_PIXIE
	RACE_HALF_OGRE
	RACE_HALF_ORC
	RACE_HALF_TROLL
	RACE_HALF_ELF
	RACE_GITH
	RACE_DROW
	RACE_SEA_ELF
	RACE_VAMPIRE
	RACE_DEMON
	RACE_LIZARDMAN
	RACE_GNOME
	RACE_ANGEL
)

// SexType represents character sex.

const (
	SEX_NEUTRAL = iota
	SEX_MALE
	SEX_FEMALE
)

// AffectedByType represents affected_by bit numbers (for extended bitvectors).

const (
	AFF_BLIND = iota
	AFF_INVISIBLE
	AFF_DETECT_EVIL
	AFF_DETECT_INVIS
	AFF_DETECT_MAGIC
	AFF_DETECT_HIDDEN
	AFF_HOLD
	AFF_SANCTUARY
	AFF_FAERIE_FIRE
	AFF_INFRARED
	AFF_CURSE
	AFF_FLAMING
	AFF_POISON
	AFF_PROTECT
	AFF_PARALYSIS
	AFF_SNEAK
	AFF_HIDE
	AFF_SLEEP
	AFF_CHARM
	AFF_FLYING
	AFF_PASS_DOOR
	AFF_FLOATING
	AFF_TRUESIGHT
	AFF_DETECTTRAPS
	AFF_SCRYING
	AFF_FIRESHIELD
	AFF_SHOCKSHIELD
	AFF_HAUS1
	AFF_ICESHIELD
	AFF_POSSESS
	AFF_BERSERK
	AFF_AQUA_BREATH
	AFF_RECURRINGSPELL
	AFF_CONTAGIOUS
	AFF_ACIDMIST
	AFF_VENOMSHIELD
	AFF_ITEM_AURAS
	AFF_PEOPLE_AURAS
	AFF_SENSE_DEAD
	AFF_HEAR_DEAD
	AFF_SEE_DEAD
	AFF_FADE
	AFF_CHAIN_AGONY
	AFF_INFEST
	AFF_GRAPPLE
	MAX_AFFECTED_BY
)

// AttackType represents mob attack types (extended bitvector bit numbers).

const (
	ATCK_BITE = iota
	ATCK_CLAWS
	ATCK_TAIL
	ATCK_STING
	ATCK_PUNCH
	ATCK_KICK
	ATCK_TRIP
	ATCK_BASH
	ATCK_STUN
	ATCK_GOUGE
	ATCK_BACKSTAB
	ATCK_FEED
	ATCK_DRAIN
	ATCK_FIREBREATH
	ATCK_FROSTBREATH
	ATCK_ACIDBREATH
	ATCK_LIGHTNBREATH
	ATCK_GASBREATH
	ATCK_POISON
	ATCK_NASTYPOISON
	ATCK_GAZE
	ATCK_BLINDNESS
	ATCK_CAUSESERIOUS
	ATCK_EARTHQUAKE
	ATCK_CAUSECRITICAL
	ATCK_CURSE
	ATCK_FLAMESTRIKE
	ATCK_HARM
	ATCK_FIREBALL
	ATCK_COLORSPRAY
	ATCK_WEAKEN
	ATCK_SPIRALBLAST
	ATCK_POUNCE
	MAX_ATTACK_TYPE
)

// DefenseType represents mob defense types (extended bitvector bit numbers).

const (
	DFND_PARRY = iota
	DFND_DODGE
	DFND_HEAL
	DFND_CURELIGHT
	DFND_CURESERIOUS
	DFND_CURECRITICAL
	DFND_DISPELMAGIC
	DFND_DISPELEVIL
	DFND_SANCTUARY
	DFND_FIRESHIELD
	DFND_SHOCKSHIELD
	DFND_SHIELD
	DFND_BLESS
	DFND_STONESKIN
	DFND_TELEPORT
	DFND_MONSUM1
	DFND_MONSUM2
	DFND_MONSUM3
	DFND_MONSUM4
	DFND_DISARM
	DFND_ICESHIELD
	DFND_GRIP
	DFND_TRUESIGHT
	DFND_ACIDMIST
	DFND_VENOMSHIELD
	MAX_DEFENSE_TYPE
)

// int represents trap damage types.

const (
	TRAP_TYPE_POISON_GAS     int = 1
	TRAP_TYPE_POISON_DART    int = 2
	TRAP_TYPE_POISON_NEEDLE  int = 3
	TRAP_TYPE_POISON_DAGGER  int = 4
	TRAP_TYPE_POISON_ARROW   int = 5
	TRAP_TYPE_BLINDNESS_GAS  int = 6
	TRAP_TYPE_SLEEPING_GAS   int = 7
	TRAP_TYPE_FLAME          int = 8
	TRAP_TYPE_EXPLOSION      int = 9
	TRAP_TYPE_ACID_SPRAY     int = 10
	TRAP_TYPE_ELECTRIC_SHOCK int = 11
	TRAP_TYPE_BLADE          int = 12
	TRAP_TYPE_SEX_CHANGE     int = 13
)

const MAX_TRAPTYPE = TRAP_TYPE_SEX_CHANGE

// ClanType represents clan types.

const (
	CLAN_PLAIN = iota
	CLAN_VAMPIRE
	CLAN_WARRIOR
	CLAN_DRUID
	CLAN_MAGE
	CLAN_CELTIC
	CLAN_DEMON
	CLAN_ANGEL
	CLAN_ARCHER
	CLAN_THIEF
	CLAN_CLERIC
	CLAN_PIRATE
	CLAN_ASSASSIN
	CLAN_UNDEAD
	CLAN_CHAOTIC
	CLAN_NEUTRAL
	CLAN_LAWFUL
	CLAN_NOKILL
	CLAN_ORDER
	CLAN_GUILD
)

// GroupType represents group types.

const (
	GROUP_CLAN = iota
	GROUP_COUNCIL
	GROUP_GUILD
)

// VariableType represents variable data types.

const (
	vtNONE = iota
	vtINT
	vtXBIT
	vtSTR
)

// MpType represents mud prog owner types.

const (
	MP_MOB = iota
	MP_ROOM
	MP_OBJ
)

// SaveType represents saving throw types.

const (
	SS_NONE = iota
	SS_POISON_DEATH
	SS_ROD_WANDS
	SS_PARA_PETRI
	SS_BREATH
	SS_SPELL_STAFF
)

// SpellDamType represents spell damage types.

const (
	SD_NONE = iota
	SD_FIRE
	SD_COLD
	SD_ELECTRICITY
	SD_ENERGY
	SD_ACID
	SD_POISON
	SD_DRAIN
)

// SpellActType represents spell action types.

const (
	SA_NONE = iota
	SA_CREATE
	SA_DESTROY
	SA_RESIST
	SA_SUSCEPT
	SA_DIVINATE
	SA_OBSCURE
	SA_CHANGE
)

// SpellPowerType represents spell power levels.

const (
	SP_NONE = iota
	SP_MINOR
	SP_GREATER
	SP_MAJOR
)

// SpellClassType represents spell class types.

const (
	SC_NONE = iota
	SC_LUNAR
	SC_SOLAR
	SC_TRAVEL
	SC_SUMMON
	SC_LIFE
	SC_DEATH
	SC_ILLUSION
)

// SpellSaveEffect represents spell save effects.

const (
	SE_NONE = iota
	SE_NEGATE
	SE_EIGHTHDAM
	SE_QUARTERDAM
	SE_HALFDAM
	SE_3QTRDAM
	SE_REFLECT
	SE_ABSORB
)

// int represents character positions.

const (
	POS_DEAD = iota
	POS_MORTAL
	POS_INCAP
	POS_STUNNED
	POS_SLEEPING
	POS_BERSERK
	POS_RESTING
	POS_AGGRESSIVE
	POS_SITTING
	POS_FIGHTING
	POS_DEFENSIVE
	POS_EVASIVE
	POS_STANDING
	POS_MOUNTED
	POS_SHOVE
	POS_DRAG
)

// Style represents fighting styles.

const (
	STYLE_BERSERK = iota
	STYLE_AGGRESSIVE
	STYLE_FIGHTING
	STYLE_DEFENSIVE
	STYLE_EVASIVE
)

// int represents room sector types.

const (
	SECT_INSIDE = iota
	SECT_CITY
	SECT_FIELD
	SECT_FOREST
	SECT_HILLS
	SECT_MOUNTAIN
	SECT_WATER_SWIM
	SECT_WATER_NOSWIM
	SECT_UNDERWATER
	SECT_AIR
	SECT_DESERT
	SECT_DUNNO
	SECT_OCEANFLOOR
	SECT_UNDERGROUND
	SECT_LAVA
	SECT_SWAMP
	SECT_MAX
)

// ItemType represents object item types.

const (
	ITEM_NONE = iota
	ITEM_LIGHT
	ITEM_SCROLL
	ITEM_WAND
	ITEM_STAFF
	ITEM_WEAPON
	ITEM_FIREWEAPON
	ITEM_MISSILE
	ITEM_TREASURE
	ITEM_ARMOR
	ITEM_POTION
	ITEM_WORN
	ITEM_FURNITURE
	ITEM_TRASH
	ITEM_OLDTRAP
	ITEM_CONTAINER
	ITEM_NOTE
	ITEM_DRINK_CON
	ITEM_KEY
	ITEM_FOOD
	ITEM_MONEY
	ITEM_PEN
	ITEM_BOAT
	ITEM_CORPSE_NPC
	ITEM_CORPSE_PC
	ITEM_FOUNTAIN
	ITEM_PILL
	ITEM_BLOOD
	ITEM_BLOODSTAIN
	ITEM_SCRAPS
	ITEM_PIPE
	ITEM_HERB_CON
	ITEM_HERB
	ITEM_INCENSE
	ITEM_FIRE
	ITEM_BOOK
	ITEM_SWITCH
	ITEM_LEVER
	ITEM_PULLCHAIN
	ITEM_BUTTON
	ITEM_DIAL
	ITEM_RUNE
	ITEM_RUNEPOUCH
	ITEM_MATCH
	ITEM_TRAP
	ITEM_MAP
	ITEM_PORTAL
	ITEM_PAPER
	ITEM_TINDER
	ITEM_LOCKPICK
	ITEM_SPIKE
	ITEM_DISEASE
	ITEM_OIL
	ITEM_FUEL
	ITEM_PUDDLE
	ITEM_ABACUS
	ITEM_MISSILE_WEAPON
	ITEM_PROJECTILE
	ITEM_QUIVER
	ITEM_SHOVEL
	ITEM_SALVE
	ITEM_COOK
	ITEM_KEYRING
	ITEM_ODOR
	ITEM_CHANCE
	ITEM_PIECE
	ITEM_HOUSEKEY
	ITEM_JOURNAL
	ITEM_DRINK_MIX
)

const MAX_ITEM_TYPE = ITEM_DRINK_MIX

// ItemExtraFlag represents object extra flags (extended bitvector bit numbers).

const (
	ITEM_GLOW = iota
	ITEM_HUM
	ITEM_DARK
	ITEM_LOYAL
	ITEM_EVIL
	ITEM_INVIS
	ITEM_MAGIC
	ITEM_NODROP
	ITEM_BLESS
	ITEM_ANTI_GOOD
	ITEM_ANTI_EVIL
	ITEM_ANTI_NEUTRAL
	ITEM_NOREMOVE
	ITEM_INVENTORY
	ITEM_ANTI_MAGE
	ITEM_ANTI_THIEF
	ITEM_ANTI_WARRIOR
	ITEM_ANTI_CLERIC
	ITEM_ORGANIC
	ITEM_METAL
	ITEM_DONATION
	ITEM_CLANOBJECT
	ITEM_CLANCORPSE
	ITEM_ANTI_VAMPIRE
	ITEM_ANTI_DRUID
	ITEM_HIDDEN
	ITEM_POISONED
	ITEM_COVERING
	ITEM_DEATHROT
	ITEM_BURIED
	ITEM_PROTOTYPE
	ITEM_NOLOCATE
	ITEM_GROUNDROT
	ITEM_LOOTABLE
	ITEM_PERMANENT
	ITEM_MULTI_INVOKE
	ITEM_DEATHDROP
	ITEM_SKINNED
	ITEM_NOFILL
	ITEM_BLACKENED
	ITEM_NOSCAVANGE
	MAX_ITEM_FLAG
)

// RoomFlag represents room flags (extended bitvector bit numbers).

const (
	ROOM_DARK = iota
	ROOM_DEATH
	ROOM_NO_MOB
	ROOM_INDOORS
	ROOM_HOUSE
	ROOM_NEUTRAL
	ROOM_CHAOTIC
	ROOM_NO_MAGIC
	ROOM_NOLOCATE
	ROOM_PRIVATE
	ROOM_SAFE
	ROOM_SOLITARY
	ROOM_PET_SHOP
	ROOM_NO_RECALL
	ROOM_DONATION
	ROOM_NODROPALL
	ROOM_SILENCE
	ROOM_LOGSPEECH
	ROOM_NODROP
	ROOM_CLANSTOREROOM
	ROOM_NO_SUMMON
	ROOM_NO_ASTRAL
	ROOM_TELEPORT
	ROOM_TELESHOWDESC
	ROOM_NOFLOOR
	ROOM_NOSUPPLICATE
	ROOM_ARENA
	ROOM_NOMISSILE
	ROOM_AUCTION
	ROOM_NOHOVER
	ROOM_PROTOTYPE
	ROOM_DND
	ROOM_TRACK
	ROOM_LIGHT
	ROOM_NOLOG
	ROOM_COLOR
	ROOM_NOWHERE
	ROOM_NOYELL
	ROOM_NOQUIT
	ROOM_NOTRACK
	ROOM_NS_CORPSE
	ROOM_NS_RECALL
)

const MAX_ROOM_FLAG = ROOM_NS_RECALL

// DirType represents directions.

const (
	DIR_NORTH = iota
	DIR_EAST
	DIR_SOUTH
	DIR_WEST
	DIR_UP
	DIR_DOWN
	DIR_NORTHEAST
	DIR_NORTHWEST
	DIR_SOUTHEAST
	DIR_SOUTHWEST
	DIR_SOMEWHERE
)

const (
	MAX_DIR    = DIR_SOUTHWEST
	DIR_PORTAL = DIR_SOMEWHERE
)

// int represents equipment wear locations.

const (
	WEAR_NONE          int = -1
	WEAR_LIGHT         int = 0
	WEAR_FINGER_L      int = 1
	WEAR_FINGER_R      int = 2
	WEAR_NECK_1        int = 3
	WEAR_NECK_2        int = 4
	WEAR_BODY          int = 5
	WEAR_HEAD          int = 6
	WEAR_LEGS          int = 7
	WEAR_FEET          int = 8
	WEAR_HANDS         int = 9
	WEAR_ARMS          int = 10
	WEAR_SHIELD        int = 11
	WEAR_ABOUT         int = 12
	WEAR_WAIST         int = 13
	WEAR_WRIST_L       int = 14
	WEAR_WRIST_R       int = 15
	WEAR_WIELD         int = 16
	WEAR_HOLD          int = 17
	WEAR_DUAL_WIELD    int = 18
	WEAR_EARS          int = 19
	WEAR_EYES          int = 20
	WEAR_MISSILE_WIELD int = 21
	WEAR_BACK          int = 22
	WEAR_FACE          int = 23
	WEAR_ANKLE_L       int = 24
	WEAR_ANKLE_R       int = 25
	MAX_WEAR           int = 26
)

// ApplyType represents apply types for affects.

const (
	APPLY_NONE = iota
	APPLY_STR
	APPLY_DEX
	APPLY_INT
	APPLY_WIS
	APPLY_CON
	APPLY_SEX
	APPLY_CLASS
	APPLY_LEVEL
	APPLY_AGE
	APPLY_HEIGHT
	APPLY_WEIGHT
	APPLY_MANA
	APPLY_HIT
	APPLY_MOVE
	APPLY_GOLD
	APPLY_EXP
	APPLY_AC
	APPLY_HITROLL
	APPLY_DAMROLL
	APPLY_SAVING_POISON
	APPLY_SAVING_ROD
	APPLY_SAVING_PARA
	APPLY_SAVING_BREATH
	APPLY_SAVING_SPELL
	APPLY_CHA
	APPLY_AFFECT
	APPLY_RESISTANT
	APPLY_IMMUNE
	APPLY_SUSCEPTIBLE
	APPLY_WEAPONSPELL
	APPLY_LCK
	APPLY_BACKSTAB
	APPLY_PICK
	APPLY_TRACK
	APPLY_STEAL
	APPLY_SNEAK
	APPLY_HIDE
	APPLY_PALM
	APPLY_DETRAP
	APPLY_DODGE
	APPLY_PEEK
	APPLY_SCAN
	APPLY_GOUGE
	APPLY_SEARCH
	APPLY_MOUNT
	APPLY_DISARM
	APPLY_KICK
	APPLY_PARRY
	APPLY_BASH
	APPLY_STUN
	APPLY_PUNCH
	APPLY_CLIMB
	APPLY_GRIP
	APPLY_SCRIBE
	APPLY_BREW
	APPLY_WEARSPELL
	APPLY_REMOVESPELL
	APPLY_EMOTION
	APPLY_MENTALSTATE
	APPLY_STRIPSN
	APPLY_REMOVE
	APPLY_DIG
	APPLY_FULL
	APPLY_THIRST
	APPLY_DRUNK
	APPLY_BLOOD
	APPLY_COOK
	APPLY_RECURRINGSPELL
	APPLY_CONTAGIOUS
	APPLY_EXT_AFFECT
	APPLY_ODOR
	APPLY_ROOMFLAG
	APPLY_SECTORTYPE
	APPLY_ROOMLIGHT
	APPLY_TELEVNUM
	APPLY_TELEDELAY
	MAX_APPLY_TYPE
)

// Condition types.

const (
	COND_DRUNK = iota
	COND_FULL
	COND_THIRST
	COND_BLOODTHIRST
	MAX_CONDS
)

// BoardType represents board types.

const (
	BOARD_NOTE = iota
	BOARD_MAIL
)

// TimerType represents timer types.

const (
	TIMER_NONE = iota
	TIMER_RECENTFIGHT
	TIMER_SHOVEDRAG
	TIMER_DO_FUN
	TIMER_APPLIED
	TIMER_PKILLED
	TIMER_ASUPRESSED
	TIMER_NUISANCE
	TIMER_CHALLENGE
)

// ChannelBit represents channel flags.

const (
	CHANNEL_AUCTION = iota
	CHANNEL_CHAT
	CHANNEL_QUEST
	CHANNEL_IMMTALK
	CHANNEL_MUSIC
	CHANNEL_ASK
	CHANNEL_SHOUT
	CHANNEL_YELL
	CHANNEL_MONITOR
	CHANNEL_LOG
	CHANNEL_HIGHGOD
	CHANNEL_CLAN
	CHANNEL_BUILD
	CHANNEL_HIGH
	CHANNEL_AVTALK
	CHANNEL_PRAY
	CHANNEL_COUNCIL
	CHANNEL_GUILD
	CHANNEL_COMM
	CHANNEL_TELLS
	CHANNEL_ORDER
	CHANNEL_NEWBIE
	CHANNEL_WARTALK
	CHANNEL_RACETALK
	CHANNEL_WARN
	CHANNEL_WHISPER
	CHANNEL_AUTH
	CHANNEL_TRAFFIC
	CHANNEL_RETIRED
	CHANNEL_DEATH
	CHANNEL_LTRAFFIC
	CHANNEL_BUG
)

// int represents PLR_ flags (extended bitvector bit numbers).

const (
	PLR_IS_NPC = iota
	PLR_BOUGHT_PET
	PLR_SHOVEDRAG
	PLR_AUTOEXIT
	PLR_AUTOLOOT
	PLR_AUTOSAC
	PLR_BLANK
	PLR_OUTCAST
	PLR_BRIEF
	PLR_COMBINE
	PLR_PROMPT
	PLR_TELNET_GA
	PLR_HOLYLIGHT
	PLR_WIZINVIS
	PLR_ROOMVNUM
	PLR_SILENCE
	PLR_NO_EMOTE
	PLR_ATTACKER
	PLR_NO_TELL
	PLR_LOG
	PLR_DENY
	PLR_FREEZE
	PLR_THIEF
	PLR_KILLER
	PLR_LITTERBUG
	PLR_ANSI
	PLR_RIP
	PLR_NICE
	PLR_FLEE
	PLR_AUTOGOLD
	PLR_AUTOMAP
	PLR_AFK
	PLR_INVISPROMPT
	PLR_ROOMVIS
	PLR_NOFOLLOW
	PLR_LANDED
	PLR_BLOCKING
	PLR_IS_CLONE
	PLR_IS_DREAMFORM
	PLR_IS_SPIRITFORM
	PLR_IS_PROJECTION
	PLR_CLOAK
	PLR_COMPASS
	PLR_NOHOMEPAGE
)

// int represents mud program types.

const (
	ACT_PROG = iota
	SPEECH_PROG
	RAND_PROG
	FIGHT_PROG
	DEATH_PROG
	HITPRCNT_PROG
	ENTRY_PROG
	GREET_PROG
	ALL_GREET_PROG
	GIVE_PROG
	BRIBE_PROG
	HOUR_PROG
	TIME_PROG
	WEAR_PROG
	REMOVE_PROG
	SAC_PROG
	LOOK_PROG
	EXA_PROG
	ZAP_PROG
	GET_PROG
	DROP_PROG
	DAMAGE_PROG
	REPAIR_PROG
	RANDIW_PROG
	SPEECHIW_PROG
	PULL_PROG
	PUSH_PROG
	SLEEP_PROG
	REST_PROG
	LEAVE_PROG
	SCRIPT_PROG
	USE_PROG
	LOAD_PROG
	LOGIN_PROG
	VOID_PROG
	TELL_PROG
	IMMINFO_PROG
	GREET_IN_FIGHT_PROG
	MOVE_PROG
	CMD_PROG
	SELL_PROG
	EMOTE_PROG
)

// Backwards compatibility aliases for prog types.
const (
	RDEATH_PROG = DEATH_PROG
	ENTER_PROG  = ENTRY_PROG
	RFIGHT_PROG = FIGHT_PROG
	RGREET_PROG = GREET_PROG
	OGREET_PROG = GREET_PROG
)

// int represents push/pull direction types.

const (
	PULL_UNDEFINED  int = 0
	PULL_VORTEX     int = 1
	PULL_VACUUM     int = 2
	PULL_SLIP       int = 3
	PULL_ICE        int = 4
	PULL_MYSTERIOUS int = 5

	PULL_CURRENT   int = PT_WATER
	PULL_WAVE      int = PT_WATER + 1
	PULL_WHIRLPOOL int = PT_WATER + 2
	PULL_GEYSER    int = PT_WATER + 3

	PULL_WIND     int = PT_AIR
	PULL_STORM    int = PT_AIR + 1
	PULL_COLDWIND int = PT_AIR + 2
	PULL_BREEZE   int = PT_AIR + 3

	PULL_LANDSLIDE  int = PT_EARTH
	PULL_SINKHOLE   int = PT_EARTH + 1
	PULL_QUICKSAND  int = PT_EARTH + 2
	PULL_EARTHQUAKE int = PT_EARTH + 3

	PULL_LAVA   int = PT_FIRE
	PULL_HOTAIR int = PT_FIRE + 1
)

// int represents spell target types.

const (
	TAR_IGNORE = iota
	TAR_CHAR_OFFENSIVE
	TAR_CHAR_DEFENSIVE
	TAR_CHAR_SELF
	TAR_OBJ_INV
)

// SkillType represents skill/spell categories.

const (
	SKILL_UNKNOWN = iota
	SKILL_SPELL
	SKILL_SKILL
	SKILL_WEAPON
	SKILL_TONGUE
	SKILL_HERB
	SKILL_RACIAL
	SKILL_DISEASE
)

// int represents damage types from attack table.

const (
	DAM_HIT = iota
	DAM_SLICE
	DAM_STAB
	DAM_SLASH
	DAM_WHIP
	DAM_CLAW
	DAM_BLAST
	DAM_POUND
	DAM_CRUSH
	DAM_GREP
	DAM_BITE
	DAM_PIERCE
	DAM_SUCTION
	DAM_BOLT
	DAM_ARROW
	DAM_DART
	DAM_STONE
	DAM_PEA
)
